/* AUTO-GENERATED by SH4Recomp — do not edit */
#ifndef SH4_RUNTIME_H
#define SH4_RUNTIME_H

#include <stdint.h>
#include <stddef.h>

#ifdef SH4RECOMP_FLYCAST
  /* When compiling inside flycast, use its actual types */
  #include "types.h"
  #include "hw/sh4/sh4_if.h"
  #include "hw/sh4/sh4_opcode_list.h"
#else
  /* Standalone mode — minimal types for compilation testing */
  typedef uint8_t u8; typedef uint16_t u16;
  typedef uint32_t u32; typedef uint64_t u64;
  typedef int32_t s32;
  typedef void (*OpCallFP)(void* ctx, u32 op);
  extern OpCallFP* OpPtr[];
  typedef struct { u32 r[16]; u32 pc; struct { u32 T; } sr; } Sh4Context;
#endif

#endif /* SH4_RUNTIME_H */
