/* AUTO-GENERATED by SH4Recomp */
#ifndef SH4_RUNTIME_H
#define SH4_RUNTIME_H

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#ifdef __cplusplus
#include <cmath>
using std::sqrtf;
#else
#include <math.h>
#endif

typedef uint8_t u8; typedef uint16_t u16;
typedef uint32_t u32; typedef uint64_t u64;
typedef int8_t s8; typedef int16_t s16;
typedef int32_t s32; typedef int64_t s64;

typedef struct {
    u32 r[16];
    u32 r_bank[8];
    u32 pc, pr, gbr, vbr, ssr, spc;
    u32 mach, macl;
    struct { u32 T:1, S:1, _:2, IMASK:4, Q:1, M:1; } sr;
    u32 fpscr, fpul;
    float fr[16], xf[16];
    s32 cycle_counter;
} Sh4Context;

/* SR read/write helpers (packs/unpacks bitfields) */
static inline u32 sh4_read_sr(Sh4Context* ctx) {
    return ctx->sr.T | (ctx->sr.S<<1) | (ctx->sr.IMASK<<4) | (ctx->sr.Q<<8) | (ctx->sr.M<<9);
}
static inline void sh4_write_sr(Sh4Context* ctx, u32 v) {
    ctx->sr.T=v&1; ctx->sr.S=(v>>1)&1; ctx->sr.IMASK=(v>>4)&0xF; ctx->sr.Q=(v>>8)&1; ctx->sr.M=(v>>9)&1;
}

/* Memory access — direct pointer into flat RAM */
#define MEM_R8(addr)  (*(u8*) (mem + ((addr) & 0x1FFFFFFF)))
#define MEM_R16(addr) (*(u16*)(mem + ((addr) & 0x1FFFFFFF)))
#define MEM_R32(addr) (*(u32*)(mem + ((addr) & 0x1FFFFFFF)))
#define MEM_W8(addr, v)  (*(u8*) (mem + ((addr) & 0x1FFFFFFF)) = (u8)(v))
#define MEM_W16(addr, v) (*(u16*)(mem + ((addr) & 0x1FFFFFFF)) = (u16)(v))
#define MEM_W32(addr, v) (*(u32*)(mem + ((addr) & 0x1FFFFFFF)) = (u32)(v))

/* sh4_interp_op declared in blocks.c (static stub) */

#endif
