/*
	MapleCast Direct Evdev Input — shortest possible input path.

	Hot loop: read(evdev_fd) → lookup table → sendto(udp_fd)
	Two syscalls. No SDL. No callbacks. No framework.

	The button mapping is loaded from the flycast mapping config file
	at startup — same file SDL uses, so the mapping is always correct.
	The config is parsed once into a static lookup table; the hot loop
	never touches it again.

	Thread runs at SCHED_FIFO priority 60. Device is grabbed exclusively
	so SDL doesn't double-read it.

	Enable: MAPLECAST_EVDEV_INPUT=1
	Override device: MAPLECAST_EVDEV_DEVICE=/dev/input/event14
*/
#ifdef __linux__

#include "maplecast_evdev_input.h"
#include "types.h"
#include "maplecast_input_sink.h"
#include "maplecast_input_server.h"
#include "input/gamepad.h"

// Gamepad globals — same ones the SH4 reads at vblank
extern u32 kcode[4];
extern u16 lt[4], rt[4];

#include <atomic>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>
#include <unordered_map>
#include <fcntl.h>
#include <unistd.h>
#include <linux/input.h>
#include <pthread.h>
#include <sched.h>
#include <sys/ioctl.h>

namespace maplecast_evdev_input
{

static int _fd = -1;
static std::thread _thread;
static std::atomic<bool> _run{false};
static std::atomic<bool> _active{false};

// ── Mapping table ────────────────────────────────────────────────────
// Built at init from the flycast config file. Maps evdev button codes
// to DC button bits. Built once, read-only in the hot loop.

// evdev EV_KEY code → DC button bit (0 = unmapped)
static uint16_t _keyMap[KEY_MAX + 1] = {};
// Digital key codes for A1/A2 (some sticks use buttons, not trigger axes)
static int _a1KeyCode = -1;
static int _a2KeyCode = -1;

// evdev ABS axis code → {dc_neg_bit, dc_pos_bit, threshold, is_trigger, trigger_slot}
struct AxisMapping {
	uint16_t negBit, posBit;   // DC dpad bits for stick axes
	int threshold;
	bool isTrigger;            // true = maps to lt/rt, not buttons
	int triggerIdx;            // 0=LT, 1=RT
};
static AxisMapping _axisMap[ABS_MAX + 1] = {};
static int _triggerAxes[2] = {-1, -1};  // axis codes for LT, RT

// DC button name → bit value
static uint16_t dcBitFromName(const char* name)
{
	if (strcmp(name, "btn_a") == 0) return DC_BTN_A;
	if (strcmp(name, "btn_b") == 0) return DC_BTN_B;
	if (strcmp(name, "btn_c") == 0) return DC_BTN_C;
	if (strcmp(name, "btn_x") == 0) return DC_BTN_X;
	if (strcmp(name, "btn_y") == 0) return DC_BTN_Y;
	if (strcmp(name, "btn_z") == 0) return DC_BTN_Z;
	if (strcmp(name, "btn_start") == 0) return DC_BTN_START;
	if (strcmp(name, "btn_d") == 0) return DC_BTN_D;
	if (strcmp(name, "btn_dpad1_up") == 0) return DC_DPAD_UP;
	if (strcmp(name, "btn_dpad1_down") == 0) return DC_DPAD_DOWN;
	if (strcmp(name, "btn_dpad1_left") == 0) return DC_DPAD_LEFT;
	if (strcmp(name, "btn_dpad1_right") == 0) return DC_DPAD_RIGHT;
	if (strcmp(name, "btn_trigger_left") == 0) return 0;   // handled as trigger axis
	if (strcmp(name, "btn_trigger_right") == 0) return 0;
	if (strcmp(name, "btn_menu") == 0) return 0;           // skip in mirror mode
	return 0;
}

// SDL button index → evdev key code (Xbox 360 layout)
// SDL joystick button indices map to these evdev codes
static uint16_t sdlBtnToEvdev(int sdlBtn)
{
	// Standard Xbox/evdev mapping
	static const uint16_t map[] = {
		BTN_SOUTH,   // 0 = A
		BTN_EAST,    // 1 = B
		BTN_WEST,    // 2 = X  (note: some drivers swap WEST/NORTH)
		BTN_NORTH,   // 3 = Y
		BTN_TL,      // 4 = LB
		BTN_TR,      // 5 = RB
		BTN_SELECT,  // 6 = Back
		BTN_START,   // 7 = Start
		BTN_THUMBL,  // 8 = LS click
		BTN_THUMBR,  // 9 = RS click
	};
	if (sdlBtn >= 0 && sdlBtn < (int)(sizeof(map)/sizeof(map[0])))
		return map[sdlBtn];
	return 0;
}

// Load the simple map file generated by evdev-mapper.
// Format: "LP=304" or "A1=axis:2" — one line per button.
static bool loadMapping(const char* path)
{
	FILE* f = fopen(path, "r");
	if (!f) return false;

	// MVC2 button name → DC bit
	// Source: docs/WEBGPU-RENDERER.md "MVC2 button layout"
	//   X=LP, Y=HP, A=LK, B=HK, LT=A1, RT=A2
	struct BtnDef { const char* name; uint16_t dcBit; };
	BtnDef defs[] = {
		{"LP",    DC_BTN_X},     // MVC2 LP = DC X
		{"HP",    DC_BTN_Y},     // MVC2 HP = DC Y
		{"LK",    DC_BTN_A},     // MVC2 LK = DC A
		{"HK",    DC_BTN_B},     // MVC2 HK = DC B
		{"UP",    DC_DPAD_UP},
		{"DOWN",  DC_DPAD_DOWN},
		{"LEFT",  DC_DPAD_LEFT},
		{"RIGHT", DC_DPAD_RIGHT},
		{"START", DC_BTN_START},
	};

	char line[256];
	while (fgets(line, sizeof(line), f)) {
		if (line[0] == '#') continue;
		char* nl = strchr(line, '\n');
		if (nl) *nl = 0;

		char btnName[16] = {};
		int code = 0;

		// Check for axis mapping: "A1=axis:2"
		if (sscanf(line, "%15[^=]=axis:%d", btnName, &code) == 2) {
			if (strcmp(btnName, "A1") == 0 && code <= ABS_MAX) {
				_triggerAxes[0] = code;
				_axisMap[code].isTrigger = true;
				_axisMap[code].triggerIdx = 0;
				printf("[evdev-input]   %s → trigger axis %d\n", btnName, code);
			}
			if (strcmp(btnName, "A2") == 0 && code <= ABS_MAX) {
				_triggerAxes[1] = code;
				_axisMap[code].isTrigger = true;
				_axisMap[code].triggerIdx = 1;
				printf("[evdev-input]   %s → trigger axis %d\n", btnName, code);
			}
			continue;
		}

		// Hat mapping: "UP=hat:17" (ABS_HAT0Y=17, etc.)
		// Hat axes are handled in the hot loop — just log them.
		if (sscanf(line, "%15[^=]=hat:%d", btnName, &code) == 2) {
			printf("[evdev-input]   %s → hat axis %d (handled in hot loop)\n", btnName, code);
			continue;
		}

		// Key mapping: "LP=304"
		if (sscanf(line, "%15[^=]=%d", btnName, &code) == 2) {
			// A1/A2 as digital keys (some sticks use buttons not triggers)
			if (strcmp(btnName, "A1") == 0) {
				if (code > 0 && code <= KEY_MAX) {
					_a1KeyCode = code;
					printf("[evdev-input]   A1 → digital key %d\n", code);
				}
				continue;
			}
			if (strcmp(btnName, "A2") == 0) {
				if (code > 0 && code <= KEY_MAX) {
					_a2KeyCode = code;
					printf("[evdev-input]   A2 → digital key %d\n", code);
				}
				continue;
			}

			for (auto& d : defs) {
				if (strcmp(btnName, d.name) == 0) {
					if (code > 0 && code <= KEY_MAX) {
						_keyMap[code] = d.dcBit;
						printf("[evdev-input]   %s → key %d → DC 0x%04x\n",
						       btnName, code, d.dcBit);
					}
					break;
				}
			}
		}
	}

	fclose(f);

	// Always map dpad hat (in case directions were mapped as hat axes)
	_axisMap[ABS_HAT0X].negBit = DC_DPAD_LEFT;
	_axisMap[ABS_HAT0X].posBit = DC_DPAD_RIGHT;
	_axisMap[ABS_HAT0Y].negBit = DC_DPAD_UP;
	_axisMap[ABS_HAT0Y].posBit = DC_DPAD_DOWN;

	printf("[evdev-input] Mapping loaded from %s\n", path);
	fflush(stdout);
	return true;
}

// ── Device detection ─────────────────────────────────────────────────

static int findJoystick()
{
	for (int i = 0; i < 32; i++) {
		char path[64];
		snprintf(path, sizeof(path), "/dev/input/event%d", i);
		int fd = open(path, O_RDONLY | O_NONBLOCK);
		if (fd < 0) continue;

		unsigned long keybit[(KEY_MAX / 8 / sizeof(unsigned long)) + 1] = {};
		ioctl(fd, EVIOCGBIT(EV_KEY, sizeof(keybit)), keybit);

		bool hasButtons = (keybit[BTN_SOUTH / (8 * sizeof(unsigned long))]
		                   >> (BTN_SOUTH % (8 * sizeof(unsigned long)))) & 1;
		if (hasButtons) {
			char name[256] = "Unknown";
			ioctl(fd, EVIOCGNAME(sizeof(name) - 1), name);
			printf("[evdev-input] Found joystick: %s at %s\n", name, path);
			close(fd);
			return open(path, O_RDONLY);  // reopen blocking
		}
		close(fd);
	}
	return -1;
}

// ── Hot loop ─────────────────────────────────────────────────────────
// Two syscalls per event batch: read() + sendto()

static uint16_t _buttons = 0xFFFF;
static uint8_t _lt = 0, _rt = 0;

static void inputLoop()
{
	struct sched_param sp{};
	sp.sched_priority = 60;
	if (pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp) == 0)
		printf("[evdev-input] thread → SCHED_FIFO priority 60\n");
	else
		printf("[evdev-input] SCHED_FIFO not granted\n");
	fflush(stdout);

	// Get trigger axis ranges for scaling
	struct input_absinfo absInfo[ABS_MAX + 1] = {};
	for (int t = 0; t < 2; t++) {
		if (_triggerAxes[t] >= 0)
			ioctl(_fd, EVIOCGABS(_triggerAxes[t]), &absInfo[_triggerAxes[t]]);
	}

	struct input_event ev;
	while (_run.load(std::memory_order_relaxed)) {
		ssize_t n = read(_fd, &ev, sizeof(ev));
		if (n != sizeof(ev)) {
			if (n < 0 && errno == EINTR) continue;
			printf("[evdev-input] device disconnected\n"); fflush(stdout);
			break;
		}

		if (ev.type == EV_KEY) {
			// Check digital A1/A2 first
			if (_a1KeyCode >= 0 && ev.code == _a1KeyCode) {
				_lt = ev.value ? 255 : 0;
			}
			else if (_a2KeyCode >= 0 && ev.code == _a2KeyCode) {
				_rt = ev.value ? 255 : 0;
			}
			else {
				uint16_t dcBit = (ev.code <= KEY_MAX) ? _keyMap[ev.code] : 0;
				if (dcBit) {
					if (ev.value)
						_buttons &= ~dcBit;
					else
						_buttons |= dcBit;
				}
			}
		}
		else if (ev.type == EV_ABS) {
			if (ev.code <= ABS_MAX && _axisMap[ev.code].isTrigger) {
				// Trigger axis → scale to 0-255
				int idx = _axisMap[ev.code].triggerIdx;
				auto& ai = absInfo[ev.code];
				int range = ai.maximum - ai.minimum;
				uint8_t scaled = (range > 0)
					? (uint8_t)((ev.value - ai.minimum) * 255 / range)
					: (uint8_t)ev.value;
				if (idx == 0) _lt = scaled;
				else          _rt = scaled;
			}
			else if (ev.code == ABS_HAT0X) {
				_buttons |= (DC_DPAD_LEFT | DC_DPAD_RIGHT);
				if (ev.value < 0) _buttons &= ~DC_DPAD_LEFT;
				if (ev.value > 0) _buttons &= ~DC_DPAD_RIGHT;
			}
			else if (ev.code == ABS_HAT0Y) {
				_buttons |= (DC_DPAD_UP | DC_DPAD_DOWN);
				if (ev.value < 0) _buttons &= ~DC_DPAD_UP;
				if (ev.value > 0) _buttons &= ~DC_DPAD_DOWN;
			}
		}
		else if (ev.type == EV_SYN && ev.code == SYN_REPORT) {
			// Write to kcode[]/lt[]/rt[] directly — works in ALL modes:
			// local play, server mode, and mirror client mode.
			// This is the fastest possible path: evdev read() → kcode[] write.
			kcode[0] = (u32)_buttons | 0xFFFF0000u;
			lt[0] = (u16)_lt << 8;
			rt[0] = (u16)_rt << 8;

			// Also feed the network paths if active
			if (maplecast_input_sink::active())
				maplecast_input_sink::directUpdate(_buttons, _lt, _rt);
			if (maplecast_input::active())
				maplecast_input::injectInput(0, _lt, _rt, _buttons);
		}
	}
}

// ── Public API ───────────────────────────────────────────────────────

bool init()
{
	if (_active.load()) return true;
	if (!std::getenv("MAPLECAST_EVDEV_INPUT")) return false;

	// Find device
	const char* devPath = std::getenv("MAPLECAST_EVDEV_DEVICE");
	if (devPath) {
		_fd = open(devPath, O_RDONLY);
		if (_fd < 0) {
			printf("[evdev-input] failed to open %s: %s\n", devPath, strerror(errno));
			return false;
		}
	} else {
		_fd = findJoystick();
		if (_fd < 0) {
			printf("[evdev-input] no joystick found\n");
			return false;
		}
	}

	char name[256] = "Unknown";
	ioctl(_fd, EVIOCGNAME(sizeof(name) - 1), name);
	printf("[evdev-input] Device: %s\n", name);

	// Load mapping from evdev-mapper output file.
	// Run: ./tools/evdev-mapper to generate this file interactively.
	const char* home = std::getenv("HOME");
	std::string mapPath = std::string(home ? home : ".") + "/.config/flycast/maplecast-evdev-map.cfg";

	if (!loadMapping(mapPath.c_str())) {
		printf("[evdev-input] No mapping at %s, using defaults\n", mapPath.c_str());
		// Default Xbox mapping
		_keyMap[BTN_SOUTH]  = DC_BTN_A;
		_keyMap[BTN_EAST]   = DC_BTN_B;
		_keyMap[BTN_WEST]   = DC_BTN_X;
		_keyMap[BTN_NORTH]  = DC_BTN_Y;
		_keyMap[BTN_TL]     = DC_BTN_Z;
		_keyMap[BTN_TR]     = DC_BTN_C;
		_keyMap[BTN_START]  = DC_BTN_START;
		_keyMap[BTN_DPAD_UP]    = DC_DPAD_UP;
		_keyMap[BTN_DPAD_DOWN]  = DC_DPAD_DOWN;
		_keyMap[BTN_DPAD_LEFT]  = DC_DPAD_LEFT;
		_keyMap[BTN_DPAD_RIGHT] = DC_DPAD_RIGHT;
		_axisMap[ABS_HAT0X].negBit = DC_DPAD_LEFT;
		_axisMap[ABS_HAT0X].posBit = DC_DPAD_RIGHT;
		_axisMap[ABS_HAT0Y].negBit = DC_DPAD_UP;
		_axisMap[ABS_HAT0Y].posBit = DC_DPAD_DOWN;
		_triggerAxes[0] = ABS_Z;
		_triggerAxes[1] = ABS_RZ;
		_axisMap[ABS_Z].isTrigger = true; _axisMap[ABS_Z].triggerIdx = 0;
		_axisMap[ABS_RZ].isTrigger = true; _axisMap[ABS_RZ].triggerIdx = 1;
	}

	// Grab exclusively so SDL doesn't double-read
	if (ioctl(_fd, EVIOCGRAB, 1) == 0)
		printf("[evdev-input] grabbed device exclusively (SDL bypassed)\n");
	else
		printf("[evdev-input] EVIOCGRAB failed — SDL may also read this device\n");
	fflush(stdout);

	_run.store(true);
	_thread = std::thread(inputLoop);
	_active.store(true);
	return true;
}

void shutdown()
{
	_run.store(false);
	if (_fd >= 0) {
		ioctl(_fd, EVIOCGRAB, 0);
		close(_fd);
		_fd = -1;
	}
	if (_thread.joinable()) _thread.join();
	_active.store(false);
}

bool active() { return _active.load(); }

} // namespace maplecast_evdev_input

#else
namespace maplecast_evdev_input {
bool init() { return false; }
void shutdown() {}
bool active() { return false; }
}
#endif
