#!/usr/bin/env bash
# ============================================================================
# setup-home-tls.sh — One-shot TLS setup for home.nobd.net
#
# Replaces stock Apache (default page) with nginx + Let's Encrypt cert,
# and proxies wss://home.nobd.net/ws to the local flycast WS server on
# 127.0.0.1:7200. After this script completes, browsers can open a direct
# WebSocket to home.nobd.net for the upstream control + input channel,
# bypassing the relay entirely.
#
# Requirements before running:
#   1. DNS A record:  home.nobd.net  →  74.101.20.197
#   2. Router port forwarding:  WAN 80 + 443  →  192.168.1.63
#
# Run as root or with sudo:
#   sudo bash scripts/setup-home-tls.sh
#
# Idempotent: safe to re-run.
# ============================================================================
set -euo pipefail

DOMAIN="home.nobd.net"
LAN_IP="192.168.1.63"
FLYCAST_PORT="7200"
EMAIL="admin@nobd.net"   # for Let's Encrypt expiry notices

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (use sudo)." >&2
  exit 1
fi

echo "==> [1/6] Sanity-check public DNS"
RESOLVED=$(getent hosts "$DOMAIN" | awk '{print $1}' | head -1)
if [[ -z "$RESOLVED" ]]; then
  echo "ERROR: $DOMAIN does not resolve. Add the A record first." >&2
  exit 2
fi
echo "    $DOMAIN → $RESOLVED"

echo "==> [2/6] Stop and disable Apache (frees port 80)"
if systemctl is-active --quiet apache2; then
  systemctl stop apache2
fi
if systemctl is-enabled --quiet apache2 2>/dev/null; then
  systemctl disable apache2
fi
echo "    apache2 stopped and disabled"

echo "==> [3/6] Install nginx + certbot"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nginx python3-certbot-nginx
systemctl enable nginx
systemctl start nginx
echo "    nginx running"

echo "==> [4/6] Obtain Let's Encrypt cert (HTTP-01 challenge via nginx)"
if [[ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]]; then
  echo "    Cert already exists for $DOMAIN — skipping issuance"
else
  certbot --nginx --non-interactive --agree-tos -m "$EMAIL" -d "$DOMAIN" \
    --redirect --keep-until-expiring
fi

echo "==> [5/6] Install final nginx config (with WebSocket /ws proxy)"
# Remove the certbot-generated default and write our own
rm -f /etc/nginx/sites-enabled/default

cat > /etc/nginx/sites-available/home.nobd.net <<NGINX
# Home flycast TLS terminator — generated by setup-home-tls.sh
# Browsers connect to wss://home.nobd.net/ws for direct upstream WS to flycast,
# bypassing the VPS relay for control + input traffic. The TA frame downstream
# still flows through the VPS relay (wss://nobd.net/ws), unchanged.

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name home.nobd.net;

    # Allow ACME renewal challenges before redirecting
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name home.nobd.net;

    ssl_certificate     /etc/letsencrypt/live/home.nobd.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/home.nobd.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # WebSocket → flycast control + input. tcp_nodelay on for low-latency input.
    location /ws {
        proxy_pass http://127.0.0.1:7200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        proxy_buffering off;
        tcp_nodelay on;
    }

    # Liveness probe — useful for browser-side LAN bypass race
    location = /health {
        add_header Cache-Control "no-store";
        return 200 "ok\n";
    }

    location / {
        return 404 "this host is the flycast TLS terminator only — see /ws\n";
    }
}
NGINX

ln -sf /etc/nginx/sites-available/home.nobd.net /etc/nginx/sites-enabled/home.nobd.net

echo "==> [6/6] Reload nginx"
nginx -t
systemctl reload nginx

echo
echo "==================================================================="
echo " Done. Verify with:"
echo "   curl -I https://home.nobd.net/health"
echo "   (should return 200 OK)"
echo
echo " WebSocket test (from another machine):"
echo "   wscat -c wss://home.nobd.net/ws"
echo
echo " Auto-renewal (certbot.timer is enabled by the package):"
echo "   systemctl status certbot.timer --no-pager | head"
echo "==================================================================="
