# -*- coding: utf-8 -*-
"""gen_cells.py -- anotak per-keyframe animation cells -> the `cell` table.

WHAT THIS IS (and what it is NOT)
---------------------------------
111,796 keyframes across 59 characters and 1,639 animation groups. Each row is
one keyframe of one animation: how long it holds, what it triggers, and where
it lives in the DAT.

It is NOT the sprite_id -> keyframe join. That was the headline reason to want
this table and it is NOT IN THIS SOURCE. Measured 2026-09-01 against the cached
HTML, not the parser: anotak's animgroup pages carry a `Sprite` column that is
EMPTY on 1,081 of 1,087 PL00 keyframe rows, and the 6 non-empty values are the
literal sentinel string "(0x7FFF: hitbox only)". `HitboxGroup` is empty on all
111,796. The parser maps both columns correctly; the data is simply not
published. Neither column is stored here -- 112k empty fields is not knowledge.

COMPACTNESS -- the point of the design
--------------------------------------
Measured field density over all 111,796 cells:

    duration        111,542 (99.8%)   62 distinct  -> always stored
    effect_trigger    8,848 ( 7.9%)  117 distinct  -> stored only when non-zero
    anim_flags        5,073 ( 4.5%)   74 distinct  -> stored only when non-zero
    render_extra      4,673 ( 4.2%)  122 distinct  -> stored only when non-zero

Omitting the zeros drops ~317,000 field writes. In a SCHEMALESS store every row
carries its own field names, so a zero written 107,000 times is 107,000 copies
of the string "anim_flags" plus a value that means "nothing happened here". The
absent field says the same thing for free.

`char` and `grp` are FIELDS, not edges. 111,796 `has_cell` edges would roughly
double the row count of the whole graph to express a parent pointer that a
field already gives you, and no query needs to traverse it.

Written as batched INSERTs (BATCH rows per statement) because 111,796
individual round-trips at ~40ms each is over an hour for data that has no
ordering constraints.

    PYTHONIOENCODING=utf-8 python tools/re_kb/ingest/gen_cells.py
    PYTHONIOENCODING=utf-8 python tools/re_kb/apply_seed.py \
        tools/re_kb/ingest/generated/anotak_cells.surql
"""
import glob
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.join(HERE, "generated", "anotak_cells.surql")

BATCH = 400


def q(v):
    """SurrealQL string literal, backslash-escaped (never '' -- see fix_quotes.py)."""
    return "'" + str(v).replace(chr(92), chr(92) * 2).replace("'", chr(92) + "'") + "'"


def num_or_str(v):
    """Keep small integers as numbers so they sort and compare; else quote."""
    s = str(v).strip()
    if re.fullmatch(r"\d{1,9}", s):
        return s
    return q(s)


def main():
    files = sorted(glob.glob(os.path.join(DATA, "anotak_PL*.json")))
    if not files:
        print("no anotak_PL*.json in %s" % DATA)
        return 2

    rows = []
    for p in files:
        m = re.search(r"(PL[0-9A-Fa-f]{2})\.json$", os.path.basename(p))
        if not m:
            continue
        cid = m.group(1)[2:].lower()
        d = json.load(io.open(p, encoding="utf-8"))
        for g in d.get("anim_groups") or []:
            gnum = g.get("group_num")
            if gnum is None:
                continue
            for i, c in enumerate(g.get("cells") or []):
                rid = "cell:pl%s_g%02x_k%03d" % (cid, gnum, i)
                f = ["id: %s" % rid,
                     "char: %s" % q("pl" + cid),
                     "grp: %s" % q("pl%s_g%02x" % (cid, gnum)),
                     "kf: %d" % i]
                anim = str(c.get("anim") or "").strip()
                if anim and anim != "keyframe%d" % i:
                    f.append("anim: %s" % q(anim))
                dur = str(c.get("duration") or "").strip()
                if dur and dur != "0":
                    f.append("dur: %s" % num_or_str(dur))
                # the sparse three -- only when they actually say something
                for key, col in (("anim_flags", "anim_flags"),
                                 ("effect_trigger", "fx_trigger"),
                                 ("render_extra", "render_extra")):
                    v = str(c.get(key) or "").strip()
                    if v and v != "0":
                        f.append("%s: %s" % (col, num_or_str(v)))
                addr = str(c.get("address") or "").strip()
                if addr:
                    f.append("addr: %s" % q(addr))
                rows.append("{ " + ", ".join(f) + " }")

    lines = [
        "-- " + "=" * 74,
        "-- anotak_cells.surql -- GENERATED by ingest/gen_cells.py. Do not hand-edit.",
        "--",
        "-- %d per-keyframe animation cells (59 chars, 1,639 groups)." % len(rows),
        "-- Zero-valued anim_flags / fx_trigger / render_extra are OMITTED, not",
        "-- stored: they are 4-8%% populated, and in a schemaless store a zero",
        "-- written 107,000 times is 107,000 copies of a field name meaning",
        "-- 'nothing happened here'.",
        "--",
        "-- sprite_id and hitbox_group are NOT stored: anotak does not publish",
        "-- them (Sprite is empty on 1,081/1,087 PL00 rows in the raw HTML; the 6",
        "-- non-empty values are the sentinel '(0x7FFF: hitbox only)').",
        "--",
        "-- No `has_cell` edges -- `char` and `grp` are fields. 111,796 edges to",
        "-- express a parent pointer would double the graph for nothing.",
        "-- " + "=" * 74,
        "USE NS re DB kb;",
        "",
        "DEFINE TABLE IF NOT EXISTS cell SCHEMALESS",
        "  COMMENT 'One anotak animation keyframe. Fields: char, grp, kf, anim, dur, "
        "anim_flags, fx_trigger, render_extra, addr. Sparse fields are ABSENT when zero. "
        "An ARTIFACT re-derivable from the ROM -- deliberately has no status.';",
        "",
    ]
    for i in range(0, len(rows), BATCH):
        chunk = rows[i:i + BATCH]
        lines.append("INSERT INTO cell [ " + ", ".join(chunk) + " ];")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    size = os.path.getsize(OUT)
    print("cells      : %d" % len(rows))
    print("statements : %d (batches of %d)" % ((len(rows) + BATCH - 1) // BATCH, BATCH))
    print("file       : %.1f MB" % (size / 1048576.0))
    print("-> %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
